#!/bin/bash

# We want to be able to call this script from anywhere but the results should always be in this directory
# Setting the full path with in the generator's -o will result in 'name' of the module being the full path which doesn't work
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
(   # contain directory change in subshell
    # shellcheck disable=SC2164
    cd "${SCRIPT_DIR}"

    PIP_GENERATOR="flatpak-builder-tools/pip/flatpak-pip-generator --checker-data --yaml"
    # Maybe there are more accurate results with the additional flag: --runtime=org.gnome.Sdk//<version>
    # Currently it makes no difference and the GHA workflow becomes unneccessarily complex with flatpaks

    # Workaround for pip's keyring bug
    export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

    # lxml must be force installed as it is in the GMOME sdk but not the platform since 41
    # Platform issue 'wontfix': https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/380
    $PIP_GENERATOR --ignore-installed=lxml lxml

    $PIP_GENERATOR pybind11 pikepdf -o python3-pikepdf-internal

    # Apply cleanup which got overwritten
    git apply pybind11-cleanup.patch
)
