#!/bin/sh

PIP_GENERATOR="flatpak-builder-tools/pip/flatpak-pip-generator --checker-data --yaml --runtime=org.gnome.Sdk//44"

# Workaround for pip's keyring bug
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

# Allow this script being called from anywhere
# Setting full path with -o will result in 'name' of the module being the full path which doesn't work
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
pushd $SCRIPT_DIR

# lxml must be force installed as it is in the GMOME 41 sdk but not the platform
$PIP_GENERATOR lxml
sed -e 's/--no-build-isolation/--no-build-isolation --ignore-installed/g' -i python3-lxml.yaml

$PIP_GENERATOR pybind11 pikepdf -o python3-pikepdf-internal

popd