# This is a collage of https://github.com/search?q=NOT+org%3Aflathub+flatpak-external-data-checker+path%3A.github&type=code

name: Run flatpak external data checker for updates

on:
  schedule:
    # Daily to keep dependencies up to date
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: /bin/bash
          args: | 
            -c "git config --global --add safe.directory /github/workspace && cd /github/workspace && 
            /app/flatpak-external-data-checker --update --never-fork qpdf.yaml &&
            /app/flatpak-external-data-checker --update --never-fork python3-pikepdf-internal.yaml"
