name: Run script to regenerate python dependencies
on: 
  schedule:
    - cron: "36 16 22 * *"  # “At 16:36 on day-of-month 22.” 
  workflow_dispatch:        # Manual trigger

jobs:
  Run-generate-pikepdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        persist-credentials: false # for create-or-update-pull-request-action
    - name: Install dependencies
      run: pip3 install requirements-parser
    - name: Run update-python-modules.sh
      run: ./generate-pikepdf

    - name: Create or Update Pull Request
      uses: gr2m/create-or-update-pull-request-action@df20b2c073090271599a08c55ae26e0c3522b329 # 1.9.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Update pikepdf Python dependencies
        body: Automatic PR by GHA
        commit-message: Regenerate pikepdf Python dependencies
        assignees: dreua